spring.application.name=video-factory
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

app.media.workspace=./media
app.media.ffmpeg-path=C:/Users/minhm/OneDrive/Documents/Developer_Imedia/TOOL/tool/vendor/ffmpeg/ffmpeg-8.1.2-essentials_build/bin/ffmpeg.exe
app.media.ffprobe-path=C:/Users/minhm/OneDrive/Documents/Developer_Imedia/TOOL/tool/vendor/ffmpeg/ffmpeg-8.1.2-essentials_build/bin/ffprobe.exe
app.media.yt-dlp-path=C:/Users/minhm/OneDrive/Documents/Developer_Imedia/TOOL/tool/vendor/yt-dlp/yt-dlp.exe
app.media.yt-dlp-cookies-from-browser=
app.media.yt-dlp-cookies-file=

app.sources.pexels-api-key=${PEXELS_API_KEY:}
app.sources.pixabay-api-key=${PIXABAY_API_KEY:}
