spring.application.name=video-factory
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

app.media.workspace=${MEDIA_WORKSPACE:./media}
app.media.ffmpeg-path=${FFMPEG_PATH:../vendor/ffmpeg/ffmpeg-8.1.2-essentials_build/bin/ffmpeg.exe}
app.media.ffprobe-path=${FFPROBE_PATH:../vendor/ffmpeg/ffmpeg-8.1.2-essentials_build/bin/ffprobe.exe}
app.media.yt-dlp-path=${YT_DLP_PATH:../vendor/yt-dlp/yt-dlp.exe}
app.media.yt-dlp-cookies-from-browser=${YT_DLP_COOKIES_FROM_BROWSER:}
app.media.yt-dlp-cookies-file=${YT_DLP_COOKIES_FILE:}

app.sources.pexels-api-key=${PEXELS_API_KEY:}
app.sources.pixabay-api-key=${PIXABAY_API_KEY:}

app.auth.enabled=true

app.auth.users[0].username=admin
app.auth.users[0].password=123
app.auth.users[0].display-name=ADMIN
app.auth.users[0].admin=true

app.auth.users[1].username=minhhv
app.auth.users[1].password=123456
app.auth.users[1].display-name=Minh Imd

app.auth.users[2].username=dupv
app.auth.users[2].password=123456
app.auth.users[2].display-name=Du Imd
